"""
Export functionality for optimization results.
Supports PDF, Markdown, and JSON formats.
"""
import json
import logging
from typing import Dict, Any, Optional
from datetime import datetime
from io import BytesIO

logger = logging.getLogger(__name__)

try:
    from reportlab.lib.pagesizes import letter, A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
    from reportlab.lib.enums import TA_CENTER, TA_LEFT
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False
    logger.warning("reportlab not available. PDF export will be disabled.")


def export_to_json(results: Dict[str, Any]) -> str:
    """
    Export optimization results to JSON format.
    
    Args:
        results: Dictionary containing optimization results
        
    Returns:
        JSON string
    """
    try:
        export_data = {
            "exported_at": datetime.utcnow().isoformat(),
            "original_prompt": results.get("original_prompt", ""),
            "prompt_type": results.get("prompt_type", ""),
            "optimized_prompt": results.get("optimized_prompt", ""),
            "quality_score": results.get("quality_score"),
            "deconstruction": results.get("deconstruction", ""),
            "diagnosis": results.get("diagnosis", ""),
            "evaluation": results.get("evaluation", ""),
            "sample_output": results.get("sample_output", ""),
            "metadata": results.get("metadata", {})
        }
        return json.dumps(export_data, indent=2, ensure_ascii=False)
    except Exception as e:
        logger.error(f"Error exporting to JSON: {str(e)}")
        raise


def export_to_markdown(results: Dict[str, Any]) -> str:
    """
    Export optimization results to Markdown format.
    
    Args:
        results: Dictionary containing optimization results
        
    Returns:
        Markdown string
    """
    try:
        md = []
        md.append("# Prompt Optimization Report\n")
        md.append(f"**Exported:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}\n")
        md.append("\n---\n")
        
        md.append("## Original Prompt\n")
        md.append(f"**Type:** {results.get('prompt_type', 'N/A').capitalize()}\n")
        md.append(f"\n```\n{results.get('original_prompt', '')}\n```\n")
        
        if results.get("quality_score"):
            md.append(f"\n## Quality Score: {results['quality_score']}/100\n")
        
        md.append("\n## Optimized Prompt\n")
        md.append(f"```\n{results.get('optimized_prompt', '')}\n```\n")
        
        if results.get("deconstruction"):
            md.append("\n## Deconstruction\n")
            md.append(f"{results['deconstruction']}\n")
        
        if results.get("diagnosis"):
            md.append("\n## Diagnosis\n")
            md.append(f"{results['diagnosis']}\n")
        
        if results.get("evaluation"):
            md.append("\n## Evaluation\n")
            md.append(f"{results['evaluation']}\n")
        
        if results.get("sample_output"):
            md.append("\n## Sample Output\n")
            md.append(f"{results['sample_output']}\n")
        
        md.append("\n---\n")
        md.append(f"*Generated by NextEleven AI Prompt Optimizer*\n")
        
        return "\n".join(md)
    except Exception as e:
        logger.error(f"Error exporting to Markdown: {str(e)}")
        raise


def export_to_pdf(results: Dict[str, Any]) -> BytesIO:
    """
    Export optimization results to PDF format.
    
    Args:
        results: Dictionary containing optimization results
        
    Returns:
        BytesIO object containing PDF data
    """
    if not REPORTLAB_AVAILABLE:
        raise ImportError("reportlab is required for PDF export. Install it with: pip install reportlab")
    
    try:
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        story = []
        
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor='#00BFA5',
            spaceAfter=30,
            alignment=TA_CENTER
        )
        
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=16,
            textColor='#00BFA5',
            spaceAfter=12,
            spaceBefore=12
        )
        
        # Title
        story.append(Paragraph("Prompt Optimization Report", title_style))
        story.append(Spacer(1, 0.2*inch))
        story.append(Paragraph(
            f"<i>Exported: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}</i>",
            styles['Normal']
        ))
        story.append(Spacer(1, 0.3*inch))
        
        # Original Prompt
        story.append(Paragraph("Original Prompt", heading_style))
        story.append(Paragraph(
            f"<b>Type:</b> {results.get('prompt_type', 'N/A').capitalize()}",
            styles['Normal']
        ))
        story.append(Spacer(1, 0.1*inch))
        story.append(Paragraph(
            results.get('original_prompt', '').replace('\n', '<br/>'),
            styles['Code']
        ))
        story.append(Spacer(1, 0.2*inch))
        
        # Quality Score
        if results.get("quality_score"):
            story.append(Paragraph(
                f"<b>Quality Score: {results['quality_score']}/100</b>",
                styles['Heading2']
            ))
            story.append(Spacer(1, 0.2*inch))
        
        # Optimized Prompt
        story.append(Paragraph("Optimized Prompt", heading_style))
        story.append(Paragraph(
            results.get('optimized_prompt', '').replace('\n', '<br/>'),
            styles['Code']
        ))
        story.append(Spacer(1, 0.2*inch))
        
        # Deconstruction
        if results.get("deconstruction"):
            story.append(PageBreak())
            story.append(Paragraph("Deconstruction", heading_style))
            story.append(Paragraph(
                results['deconstruction'].replace('\n', '<br/>'),
                styles['Normal']
            ))
            story.append(Spacer(1, 0.2*inch))
        
        # Diagnosis
        if results.get("diagnosis"):
            story.append(Paragraph("Diagnosis", heading_style))
            story.append(Paragraph(
                results['diagnosis'].replace('\n', '<br/>'),
                styles['Normal']
            ))
            story.append(Spacer(1, 0.2*inch))
        
        # Evaluation
        if results.get("evaluation"):
            story.append(Paragraph("Evaluation", heading_style))
            story.append(Paragraph(
                results['evaluation'].replace('\n', '<br/>'),
                styles['Normal']
            ))
            story.append(Spacer(1, 0.2*inch))
        
        # Sample Output
        if results.get("sample_output"):
            story.append(PageBreak())
            story.append(Paragraph("Sample Output", heading_style))
            story.append(Paragraph(
                results['sample_output'].replace('\n', '<br/>'),
                styles['Normal']
            ))
        
        # Footer
        story.append(Spacer(1, 0.3*inch))
        story.append(Paragraph(
            "<i>Generated by NextEleven AI Prompt Optimizer</i>",
            styles['Normal']
        ))
        
        doc.build(story)
        buffer.seek(0)
        return buffer
    except Exception as e:
        logger.error(f"Error exporting to PDF: {str(e)}")
        raise


def export_results(results: Dict[str, Any], format: str = "json") -> Any:
    """
    Export optimization results in the specified format.
    
    Args:
        results: Dictionary containing optimization results
        format: Export format ('json', 'markdown', or 'pdf')
        
    Returns:
        Exported data (string for json/markdown, BytesIO for pdf)
    """
    format = format.lower()
    
    if format == "json":
        return export_to_json(results)
    elif format == "markdown":
        return export_to_markdown(results)
    elif format == "pdf":
        return export_to_pdf(results)
    else:
        raise ValueError(f"Unsupported export format: {format}. Supported formats: json, markdown, pdf")
